name: tmate-ssh-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: self-actuated/connect-ssh@master

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
