name: tmate-ssh-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create debug output
        id: debug
        run: |
          echo $RUNNER_DEBUG
          echo "RUNNER_DEBUG=$RUNNER_DEBUG" >> "$GITHUB_OUTPUT"

      - name: Setup tmate session
        if: steps.debug.outputs.RUNNER_DEBUG == 1
        uses: mxschmitt/action-tmate@v3
